name: Create GDS file

on:
  push:
    branches: ['main']
    paths-ignore:
    - 'README.md'

jobs:
  create_gds:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: install curl
        run: sudo apt-get update && sudo apt-get install -y curl 
      
      - name: install nix environment
        run: |
          curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install --no-confirm --extra-conf "\
          extra-substituters = https://openlane.cachix.org\
          extra-trusted-public-keys = openlane.cachix.org-1:qqdwh+QMNGmZAuyeQJTH9ErW57OWSvdtuwfBKdS254E=\
          "
      - name: Set up Nix
        run: |
          git clone https://github.com/efabless/openlane2
          cd openlane2
          nix-shell
          openlane --smoke-test
          ls

      - name: Create GDS file
        run: |
          cd
          pwd
          ls
          cd openlane
          openlane openlane --flow VHDLClassic config.json

      - name: Workflow got to the end Successfully ✅
        run: echo "Workflow ended !"