name: Create GDS file

on:
  push:
    branches: ['main']
    paths-ignore:
    - 'README.md'

jobs:
  create_gds:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Debug
        run: |
          echo "Current directory: $(pwd)"
          echo "List files: $(ls -l)"
          echo "List Root files: $(ls -l /)"
          
      - name: Set up Nix
        run: |
          git clone https://github.com/efabless/openlane2
          ls
          cd openlane2
          nix develop --accept-flake-config --system x86_64-linux   

      - name: check OpenLane
        run: |
          ls
          openlane --smoke-test
          ls

      - name: Create GDS file
        run: |
          cd
          pwd
          ls
          cd openlane
          openlane --flow VHDLClassic config.json
    
      - name: Workflow got to the end Successfully ✅
        run: echo "Workflow ended !"